version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.9 /usr/local/share/virtualenvs/tap-kustomer
            source /usr/local/share/virtualenvs/tap-kustomer/bin/activate
            uv pip install -U 'pip==22.2.2' 'setuptools==65.3.0'
            uv pip install .[dev]
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-kustomer/bin/activate
            pylint tap_kustomer -d C,R,W
workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
